# Generated by Django 5.1.3 on 2025-01-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('picture', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=200)),
                ('lvl', models.IntegerField(choices=[(0, 'Guest'), (1, 'Customer'), (2, 'Admin'), (3, 'Master')], default=0)),
            ],
        ),
    ]
