# Generated by Django 5.1.5 on 2025-01-19 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tisch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tisch_id', models.CharField(max_length=10, unique=True)),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
                ('kapazität', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Buchung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('zeitfenster', models.TimeField()),
                ('dauer', models.IntegerField()),
                ('tisch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seating.tisch')),
            ],
        ),
    ]
