# Generated by Django 5.1.5 on 2025-01-20 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0004_fill_tische'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tisch',
            old_name='kapazität',
            new_name='kapazitat',
        ),
    ]
