# Generated by Django 5.1.5 on 2025-01-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0005_rename_kapazität_tisch_kapazitat'),
    ]

    operations = [
        migrations.AddField(
            model_name='buchung',
            name='buchungscode',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
    ]
